version: '3.8'

services:
  flask-app:
    build: .
    container_name: app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV
      - OPENAI_API_KEY
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"

